# Generated by Django 4.0.5 on 2022-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coitask', '0002_remove_doctor_cat_category_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='cat',
            field=models.ManyToManyField(blank=True, related_name='categorys', to='coitask.category'),
        ),
    ]
