# Generated by Django 4.0.5 on 2022-06-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coitask', '0003_remove_category_doctors_doctor_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['birthday']},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cat',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='coitask.category'),
        ),
    ]
