# Generated by Django 4.0.5 on 2022-07-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coitask', '0004_alter_doctor_options_alter_doctor_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Specialization',
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Doctor specialization', 'verbose_name_plural': 'Doctor specialization'},
        ),
    ]
